# Generated by Django 5.0.3 on 2024-03-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=124, max_digits=128)),
                ('longitude', models.DecimalField(decimal_places=124, max_digits=128)),
                ('name', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=128)),
            ],
        ),
    ]
